[tool.pytest.ini_options]
minversion = "7.4.4"
addopts = "-vv -rf --color=yes"
testpaths = [
    "tests"
]
python_files = "tests.py"

[tool.isort]
profile = "black"
src_paths = ["."]
force_alphabetical_sort_within_sections = true
group_by_package = true
virtual_env = "pipenv"
honor_noqa = true
color_output = true
skip_glob = ["__pycache__/*", "instance/*", "*.pyc", "migrations/*"]

[tool.black]
target-version = ["py311"]
required-version = "24.8.0"
exclude = '''
(
    instance/.*
    | migrations/.*
    | __pycache__/.*
    | .*\.pyc
)
'''
